apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  flowLogsFlushInterval: 15s
  flowLogsFileAggregationKindForAllowed: 1
  flowLogsFileAggregationKindForDenied: 0
  flowLogsCollectTcpStats: true
  flowLogsEnableHostEndpoint: true
  dnsLogsFlushInterval: 15s
  dnsLogsFileEnabled: true
  dnsLogsFileAggregationKind: 0
  logSeverityScreen: Info
  captureRotationSeconds: 3600
  l7LogsFlushInterval: 15s
  l7LogsFileAggregationHTTPHeaderInfo: IncludeL7HTTPHeaderInfo
  policySyncPathPrefix: /var/run/nodeagent
---
apiVersion: operator.tigera.io/v1
kind: ApplicationLayer
metadata:
  name: tigera-secure
spec:
  logCollection:
    collectLogs: Enabled
    logIntervalSeconds: 5
    logRequestsPerInterval: -1